add_newline = false
palette = 'onedark'

format = """\
$directory$git_branch$git_status$git_metric$spython$nodejs$java$php$rust$golang$package$cmd_duration$character"""

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[directory]
style = 'fg:blue'
format = '[ $path]($style)'
truncation_length = 1
# truncation_symbol = '…/'
home_symbol = ' ~'
read_only = '🔒 '
read_only_style = 'red'

[directory.substitutions]
'Documentos' = ' '
'Descargas'  = ' '
'Música'     = ' '
'Imágenes'   = ' '
'Vídeos'     = ' '
'Escritorio' = ' '
'Plantillas' = ' '
'Público'    = ' '

[git_branch]
symbol = ' '
style = 'fg:#98c379'
format = '[ $symbol$branch ]($style)'

[git_status]
style = 'fg:#e5c07b'
format = '([$staged$modified $untracked$deleted$ahead_behind]($style))'
staged     = '[ $count](fg:#98c379)'
modified   = '[ $count](fg:#61afef)'
untracked  = '[ $count](fg:#c678dd)'
deleted    = '[ $count](fg:#d19a66)'
ahead      = '[⇡$count](fg:#a3be8c)'
behind     = '[⇣$count](fg:#bf616a)'
diverged   = '[⇕$count](fg:#e5c07b)'

[git_metrics]
disabled = false
only_nonzero_diffs = true
format = '[  $added ]($added_style)[  $deleted ]($deleted_style)'
added_style = 'fg:#A3BE8C'
deleted_style = 'fg:#BF616A'

[python]
symbol = ' '
style = 'fg:#f0e68c'
format = '[ $symbol$version ]($style)'

[nodejs]
symbol = ' '
style = 'fg:#8cc84b'
format = '[ $symbol$version ]($style)'

[java]
symbol = ' '
style = 'fg:#b07219'
format = '[ $symbol$version ]($style)'

[php]
symbol = ' '
style = 'fg:#8892be'
format = '[ $symbol$version ]($style)'

[rust]
symbol = ' '
style = 'fg:#dea584'
format = '[ $symbol$version ]($style)'

[golang]
symbol = ' '
style = 'fg:#00acd7'
format = '[ $symbol$version ]($style)'

[package]
symbol = '󰏗 '
format = '[ $symbol$version ](white)'

[cmd_duration]
min_time = 500
style = 'gray'
format = '[ ⏱ $duration ]($style)'

[palettes.onedark]
blue = '#61afef'
green = '#98c379'
yellow = '#e5c07b'
red = '#e06c75'
purple = '#c678dd'
gray = '#828997'
white = '#abb2bf'
black = '#2c323c'

[palettes.nord]
blue = '#81A1C1'
green = '#A3BE8C'
yellow = '#EBCB8B'
red = '#BF616A'
purple = '#B48EAD'
gray = '#4C566A'
white = '#D8DEE9'
black = '#2E3440'

[palettes.github_dark]
blue = '#4078c0'
green = '#28a745'
yellow = '#dbab09'
red = '#d73a49'
purple = '#6f42c1'
gray = '#6a737d'
white = '#e1e4e8'
black = '#24292e'

[palettes.tokyonight]
blue = '#7aa2f7'
green = '#9ece6a'
yellow = '#e0af68'
red = '#f7768e'
purple = '#bb9af7'
gray = '#565f89'
white = '#c0caf5'
black = '#1a1b26'
